DROP DATABASE IF EXISTS myBusiness_db;
CREATE DATABASE myBusiness_db;

USE myBusiness_db;

CREATE TABLE department (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(30) NOT NULL,
 salary DECIMAL NOT NULL,
 department_id INT NOT NULL,
 FOREIGN KEY (department_id)
 REFERENCES department(id)
 ON DELETE SET NULL
);

CREATE TABLE employee(
 id AUTO_INCREMENT INT NOT NULL,
 first_name VARCHAR(30) NOT NULL,
 last_name VARCHAR(30) NOT NULL,
 role_id INT NOT NULL,
 manager_id INT NOT NULL
 FOREIGN KEY (role_id)
 REFERENCES role(id)
 ON DELETE SET NULL
);